// Generated by LazyStack - modifications will be overwritten
using Microsoft.Extensions.DependencyInjection;

namespace __NameSpace__
{
    public partial class Startup
    {
        public void ConfigureSvcs(IServiceCollection services)
        {
__ServiceRegistrations__
        }
    }
}
