/* 
 * Originally Generated by: https://github.com/openapitools/openapi-generator.git
 * Modified by LazyStack
 */


using System;

namespace __ProjName__.Client
{
    /// <summary>
    /// A delegate to ExceptionFactory method
    /// </summary>
    /// <param name="methodName">Method name</param>
    /// <param name="response">Response</param>
    /// <returns>Exceptions</returns>
    public delegate Exception ExceptionFactory(string methodName, IApiResponse response);
}
