/* 
 * Originally Generated by: https://github.com/openapitools/openapi-generator.git
 * Modified by LazyStack
 */
using System;

namespace __ProjName__.Client
{
    /// <summary>
    /// Represents configuration aspects required to interact with the API endpoints.
    /// </summary>
    public interface IApiAccessor
    {
        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        ExceptionFactory ExceptionFactory { get; set; }
    }
}
