// Generated by LazyStack - modifications will be overwritten
using Microsoft.Extensions.DependencyInjection;

namespace LazyStackWebApi
{
    public partial class Startup
    {
        public void ConfigureSvcs(IServiceCollection services)
        {

        }
    }
}
